project 'santak.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'santak' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for santak
  pod 'SwiftyJSON'
  
  #using Sync to copy JSON to core data
  pod 'Sync', '~> 2'
  pod 'DATAStack', '~> 6'

  target 'santakTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'santakUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
